### ISSUE TITLE
Servant 0.12 support?

### ISSUE THREAD

**Issue by srid** [Compositional/reflex-servant#5]
Servant 0.13 doesn't work with latest jsaddle (in reflex-platform) due to a conflicting dependency constraint on `http-types`.

jsaddle uses `http-types >=0.8.6 && <0.12`

servant-0.13 uses `http-types ==0.12.*`.

**Comment by roberth** [comment]
Right. `reflex-servant` only depends on parts of `http-types` that are very stable, as far as I know, so that part should be trivial. I don't know off the top of my head what has changed in Servant itself from 0.12 to 0.13, but I expect support for Servant 0.12 to be straightforward to add, if not trivial.

**Comment by roberth** [comment]
I gave it a shot, but it didn't work out as I hoped. GHC gets stuck on some type family terms during compilation, but not in GHCi. If anyone wants to investigate, my changes are on [a branch](https://github.com/Compositional/reflex-servant/tree/experimentation-servant-0.12).

**Comment by srid** [comment]
Once my PR to JSaddle (linked above) gets merged we shouldn't strictly need this.

**Comment by roberth** [comment]
Thanks for the http-types bump in jsaddle!

**Comment by roberth** [comment]
Closing this as wontfix due to a non-trivial stuck types issue triggered by servant 0.12. A fix may be possible still, but neither of us can spend time on it.
